config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  root 'pages#one'
  get 'pages/three'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-inverse">
      <%= link_to 'one', pages_one_url %>
      <%= link_to 'two', pages_two_url %>
      <%= link_to 'three', pages_three_url %>
    </nav>
    
    <%= yield %>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous">
  </script>
  
  </body>
</html>

app/views/pages/one.html.erb
<h1>Felipe Esteban Martinez Quiñones</h1>

app/views/pages/three.html.erb
<h2>Soy la página three</h2>

<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus feugiat in ante metus dictum at. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Purus gravida quis blandit turpis cursus in hac. Placerat vestibulum lectus mauris ultrices. Sed adipiscing diam donec adipiscing tristique. Cursus eget nunc scelerisque viverra. Luctus accumsan tortor posuere ac ut consequat. Dolor morbi non arcu risus quis varius. Diam vulputate ut pharetra sit amet aliquam id. Tristique risus nec feugiat in fermentum posuere urna nec. </p>

app/views/pages/two.html.erb
<%= image_tag 'rake_routes_25082021.png' %>